server:
  servlet:
    context-path: '/api/v1'
  port: 8082

spring:
  application:
    name: 'order-service'
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/order_db
    username: 'postgres'
    password: '@3563949Zx'
  jpa:
    hibernate:
      ddl-auto: update

rest-client:
  inventory-service-name: 'inventory-service'
  inventory-service-url: 'http://${rest-client.inventory-service-name}/api/v1/inventories'

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
  api-docs:
    path: '/api-docs'

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8716/eureka'
