server:
  servlet:
    context-path: '/api/v1'
  port: 8082

spring:
  application:
    name: 'order-service'
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/order_db
    username: 'postgres'
    password: '@3563949Zx'
  jpa:
    hibernate:
      ddl-auto: update

spring.kafka:
  bootstrap-servers: 'localhost:9092'

rest-client:
  product-service-name: 'product-service'
  product-service-url: 'http://${rest-client.product-service-name}/api/v1/products'

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
  api-docs:
    path: '/api-docs'

eureka.client.service-url:
  default-zone: 'http://eureka:3563949Zx@localhost:8761/eureka'

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

resilience4j.circuit-breaker:
  instances:
    inventory:
      register-health-indicator: true
      event-consumer-buffer-size: 10
      sliding-window-type: count_based
      sliding-window-size: 5
      failure-rate-threshold: 50
      wait-duration-in-open-state: 1s
      permitted-number-of-calls-in-half-open-state: 3
      automatic-transition-from-open-to-half-open-enabled: true

resilience4j.retry:
  instances:
    inventory:
      max-attempts: 3
      wait-duration: 1s
