server:
  servlet:
    context-path: '/api/v1'
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/order_db
    username: 'postgres'
    password: '@3563949Zx'
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
  api-docs:
    path: '/api-docs'
