server:
  servlet:
    context-path: '/api/v1'
  port: 8084

spring:
  application:
    name: 'product-service'
  data:
    mongodb:
      uri: 'mongodb://localhost:27017/product_db'
      auto-index-creation: true
  cache:
    type: redis
    couchbase:
      expiration: '864000'
  kafka:
    bootstrap-servers: 'localhost:9092'

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
  api-docs:
    path: '/api-docs'

eureka.client.service-url:
  default-zone: 'http://eureka:3563949Zx@localhost:8761/eureka'