server:
  servlet:
    context-path: '/api/v1'
  port: 8084

spring:
  application:
    name: 'product-service'
  data:
    mongodb:
      uri: 'mongodb://localhost:27017/product_db'

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
  api-docs:
    path: '/api-docs'

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8716/eureka'